name: Bug Parser
description: For a bug parser
title: "[Bug]: "
labels: ["bug parser", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug parser report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
    validations:
      required: true
  - type: dropdown
    id: soft_browsers
    attributes:
      label: What soft is concerned 
      multiple: true
      options:
        - spm
        - fsl
        - afni