name: Bug Parser
description: For a bug parser
title: "[Bug]: "
labels: ["bug parser", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug parser report!+
        
  - type: textarea
    id: batch-name
    attributes:
      label: batch name and line
      description: 
      placeholder: Tell us where is the **spm/fsl/afni batch** fil, and the **lines** to check ?   
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe or **attach image** file of the happening bug.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: ground-truth
    attributes:
      label: Describe the expected ground-truth ? 
      description: Describe or **attach image** file of the ground-truth.
      placeholder: Tell us what you see!
      value: "The expected ground-truth : "
    validations:
      required: true
  - type: dropdown
    id: soft_browsers
    attributes:
      label: What soft is concerned 
      multiple: true
      options:
        - SPM
        - FSL
        - AFNI